name: busha_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_auth: ^4.19.6
  firebase_core: ^2.31.1
  cloud_firestore: ^4.17.4
  http: ^1.2.1
  intl: ^0.19.0
  google_fonts: ^6.2.1
  get_it: ^7.7.0
  flutter_splash_screen: ^3.0.0
  skeletonizer: ^1.1.2+1
  shared_preferences: ^2.2.3
  json_annotation: ^4.9.0
  fluttertoast: ^8.2.5
  page_transition: ^2.1.0
  flutter_settings_ui: ^3.0.1
  webview_flutter: ^4.8.0
  pretty_print_json: ^1.0.1
  badges: ^3.1.2
  flutter_analog_clock: ^1.0.3
  flutter_svg: ^2.0.10+1
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.1
  email_validator: ^2.1.17
  welltested_annotation: ^1.1.0
  firebase_auth_mocks: ^0.13.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.10
  mockito: ^5.4.4
  mocktail: ^1.0.3

flutter:

  uses-material-design: true

  assets:
     - assets/
     - assets/logos/
     - .env

